# Generated by Django 3.2 on 2021-04-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
