# Generated by Django 3.2 on 2021-04-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0002_auto_20210427_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
