# Generated by Django 3.2 on 2021-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Autoterra', '0003_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Animal'],
            },
        ),
        migrations.CreateModel(
            name='Valeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Niveau', models.TextField(help_text='Définir le niveau humidité')),
            ],
            options={
                'ordering': ['Niveau'],
            },
        ),
    ]
