# Generated by Django 3.2 on 2021-04-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0004_blibliotheque_valeurs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blibliotheque',
            options={'ordering': ['Animal', 'Humidite']},
        ),
        migrations.AddField(
            model_name='blibliotheque',
            name='Humidite',
            field=models.CharField(help_text='Humidite', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blibliotheque',
            name='Animal',
            field=models.CharField(help_text='Animal', max_length=100),
        ),
    ]
