# Generated by Django 3.2 on 2021-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0007_delete_blibliotheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.CharField(help_text='Animal', max_length=100)),
                ('Image', models.ImageField(upload_to='')),
                ('Humidite', models.CharField(help_text='Humidite', max_length=100)),
            ],
            options={
                'ordering': ['Animal', 'Image', 'Humidite'],
            },
        ),
    ]
