# Generated by Django 3.2 on 2021-04-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0008_blibliotheque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blibliotheque',
        ),
    ]
