# Generated by Django 3.2 on 2021-05-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0010_bibliotheque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bibliotheque',
        ),
    ]
