# Generated by Django 3.2 on 2021-05-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0012_bibliotheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_niv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niv_inf', models.IntegerField(help_text='Pourcentage min recherché')),
                ('niv_sup', models.IntegerField(help_text='Pourcentage max recherché')),
            ],
            options={
                'ordering': ['niv_inf', 'niv_sup'],
            },
        ),
        migrations.DeleteModel(
            name='Bibliotheque',
        ),
        migrations.DeleteModel(
            name='Valeurs',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autoterra.question_niv'),
        ),
    ]
