# Generated by Django 3.2 on 2021-05-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0013_auto_20210503_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.CharField(help_text='Animal', max_length=100)),
                ('Image', models.ImageField(upload_to='')),
                ('Humidite_min', models.IntegerField(help_text='Humidite pourcentage min')),
                ('Humidite_max', models.IntegerField(help_text='Humidite pourcentage max')),
            ],
            options={
                'ordering': ['Animal', 'Image', 'Humidite_min', 'Humidite_max'],
            },
        ),
    ]
