# Generated by Django 3.2 on 2021-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0015_auto_20210503_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affichage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Humidite', models.IntegerField(help_text='Humidite')),
                ('Temperature', models.IntegerField(help_text='Température')),
            ],
            options={
                'ordering': ['Humidite', 'Temperature'],
            },
        ),
    ]
