# Generated by Django 3.2 on 2021-05-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0016_affichage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affichage',
        ),
    ]
