# Generated by Django 3.2 on 2021-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoterra', '0017_delete_affichage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affichage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Nom', max_length=100)),
                ('Humidite', models.IntegerField(help_text='Humidite')),
                ('Temperature', models.IntegerField(help_text='Température')),
            ],
            options={
                'ordering': ['Title', 'Humidite', 'Temperature'],
            },
        ),
    ]
